steps:
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER%%io}/${CI_REPO_NAME%%-service}"
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [master, main]
